### ISSUE TITLE
Devil design

### ISSUE THREAD

**Issue by boelle** [rmoravcik/Slic3r-settings#1]
Hi

any chance you also have settings for DD white and black PLA ?

i got almost perfect settings but i struggle with to much cooling during the first 5mm

testing green PLA from DD right now and if you can use it i could share my settings for that

**Comment by rmoravcik** [comment]
Hi,

I'm sorry, I don't have settings for PLA from DD. To be honest I have only PETG from them.

Did you try one of my PLA settings and just change hotend and bed temperature? All my PLA settings are basically the same and worked fine with PLA samples from different vendors.

**Comment by boelle** [comment]
Hi

No i had one of the PLA from DD allready so i just worked from that, but yes you are right that once you get one correct the same settings work pretty well with others too

my struggle is that during the first 5mm the plastic shrinks to much but then rest of print is ok 

i have tried to get help on danish facebook pages but so far no luck on tips on how i can improve
